// File generated by FlutterFire CLI (run: dart run flutterfire_cli:configure).
// Replace this file by running in project root:
//   dart run flutterfire_cli:configure
// or: flutterfire configure
//
// Until then, this placeholder allows the app to compile.
// After running flutterfire configure, this file will contain your project's
// Firebase options for each platform.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'PLACEHOLDER_REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
      appId: '1:000000000000:web:0000000000000000000000',
      messagingSenderId: '000000000000',
      projectId: 'your-project-id',
      authDomain: null,
      databaseURL: null,
      storageBucket: 'your-project-id.appspot.com',
      measurementId: null,
      trackingId: null,
    );
  }
}
